---
- hosts: localhost
  connection: local
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes
        state: present

    - name: Install Docker python
      apt:
        name: python3-docker
        update_cache: yes
        state: present

    - name: Create network for ELK stack
      docker_network:
        name: elk

    - name: Build Elasticsearch Docker image
      docker_image:
        name: es-custom
        tag: latest
        path: ./roles/elasticsearch/files/


    - name: Run Elasticsearch containers
      docker_container:
        name: "elasticsearch{{ item }}"
        image: es-custom:latest
        state: started
        restart_policy: always
        env:
          node.name: "es{{ item }}"
          cluster.name: "es-cluster"
          ES_JAVA_OPTS: "-Xms1g -Xmx1g"
          discovery.seed_hosts: "elasticsearch1,elasticsearch2,elasticsearch3"
          cluster.initial_master_nodes: "es1,es2,es3"
        networks:
          - name: elk
        ports:
          - "{{ 9200 + item }}:9200"
      loop: "{{ range(1, 4)|list }}"
