- name: Build image from local Dockerfile
  docker_image:
     path: ./roles/kibana/image/
     name: kibanaimage
     state: present

- name: Run Logstash container
  docker_container:
    name: "kibana"
    image: kibanaimage
    state: started
    restart_policy: always
    networks:
      - name: elk
    volumes:
      - ./roles/kibana/files/kibana.yml:/etc/kibana/kibana.yml
    ports:
      - "5601:5601"
