version: '3'
services:
  elasticsearch1:
    build: .
    container_name: elasticsearch1
    networks:
      elk:
        ipv4_address: 172.20.0.3
    ports:
    - "9201:9200"

  elasticsearch2:
    build: .
    container_name: elasticsearch2
    networks:
      elk:
        ipv4_address: 172.20.0.4
    ports:
    - "9202:9200"

  elasticsearch3:
    build: .
    container_name: elasticsearch3
    networks:
      elk:
        ipv4_address: 172.20.0.5
    ports:
    - "9203:9200"

networks:
  elk:
    ipam:
      config:
        - subnet: 172.20.0.0/24
