- name: Build image from local Dockerfile
  docker_image:
     path: ./roles/prometheus/image/
     name: promeimage
     state: present

- name: Run Prometheus container
  docker_container:
    name: "prometheus"
    image: promeimage
    state: started
    restart_policy: always
    networks:
      - name: elk
    volumes:
      - ./roles/prometheus/files/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
