- name: Configure Elasticsearch for clustering
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: '0644'

- name: Restart Elasticsearch container
  docker_container:
    name: "{{ inventory_hostname }}"
    state: restarted