- name: Install sudo package
  apt:
    name: sudo
    state: present

- name: Configure Elasticsearch for clustering
  template:
    src: ./roles/elasticsearch/files/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: '0644'

- name: Start Elasticsearch container
  become_user: elasticsearch
  command: /usr/share/elasticsearch/bin/elasticsearch

