- name: Create network for ELK stack
  docker_network:
     name: elk

- name: Build image from local Dockerfile
  docker_image:
     path: ./roles/elasticsearch/image/
     name: elasticimage
     state: present

- name: Render elasticsearch.yml template
  template:
    src: ./roles/elasticsearch/templates/elasticsearch.yml.j2
    dest: ./roles/elasticsearch/files/elasticsearch{{ item }}.yml
  loop: "{{ range(1, 4)|list }}"

- name: Run Elasticsearch containers
  docker_container:
    name: "elasticsearch{{ item }}"
    image: elasticimage
    state: started
    restart_policy: always
    env:
      node.name: "es{{ item }}"
      cluster.name: "es-cluster"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.seed_hosts: "elasticsearch1,elasticsearch2,elasticsearch3"
      cluster.initial_master_nodes: "es1,es2,es3"
    networks:
      - name: elk
    ports:
      - "{{ 9200 + item }}:9200"
    volumes:
      - ./roles/elasticsearch/files/elasticsearch{{ item }}.yml:/etc/elasticsearch/elasticsearch.yml
  loop: "{{ range(1, 4)|list }}"
