    - name: Install Docker
      apt:
        name:
          - docker.io
        state: present

    - name: Install Docker python
      apt:
        name: python3-docker
        state: present

    - name: Create network for ELK stack
      docker_network:
         name: elk
