    - name: Install Docker
      apt:
        name:
          - docker.io
        state: present

    - name: Install Docker python
      apt:
        name: python3-docker
        state: present

    - name: Create network for ELK stack
      docker_network:
         name: elk
         
    - name: Increase vm.max_map_count
      sysctl:
        name: vm.max_map_count
        value: 262144
        state: present